dependencies:
- name: fmtok8s-api-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.124
- name: fmtok8s-agenda-rest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: fmtok8s-c4p-rest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: fmtok8s-email-rest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: zeebe-cloud-events-router
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.51   